FROM php:7.2.2-fpm
ENV TZ 'Asia/Taipei'
CMD cron -f & php-fpm
RUN apt-get update && apt-get install -y mysql-client --no-install-recommends \
  && curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/3.1.3.tar.gz \
  && tar xfz /tmp/redis.tar.gz \
  && rm -r /tmp/redis.tar.gz \
  && mkdir -p /usr/src/php/ext \
  && mv phpredis-3.1.3 /usr/src/php/ext/redis \
  && apt-get install -y sendmail libpng-dev \
  && apt-get install -y libmagickwand-dev --no-install-recommends \
  && apt-get install -y libfreetype6-dev \
  && apt-get install -y libjpeg62-turbo-dev \
  && apt-get install -y libpng-dev \
  && apt-get install -y pngquant \
  && apt-get install -y gifsicle \
  && pecl install imagick \
  && apt-get update && apt-get install -y zlib1g-dev \
  && docker-php-ext-install pdo_mysql redis gd pcntl zip\
  && docker-php-ext-enable imagick\
  && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install -j$(nproc) gd \
  && echo "memory_limit = 512M\n" \
     "upload_max_filesize = 50M\n" \
     "post_max_size = 50M\n" \
     "max_execution_time = 600\n" \
     > /usr/local/etc/php/conf.d/uploads.ini \
  && apt-get install vim -y \
  && apt-get install -y cron \
  && apt-get install rsyslog -y \
  && sed -i '/session    required     pam_loginuid.so/c\#session    required   pam_loginuid.so' /etc/pam.d/cron \
  && echo "* * * * * root cd /var/www && php artisan schedule:run >> /dev/null 2>&1" >> /etc/crontab
